# Generated by Django 5.0.4 on 2024-04-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_book_description_alter_book_author_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Author Name')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type',
            field=models.CharField(choices=[('hardback', 'Hardback'), ('paperback', 'Paperback'), ('special', 'Special')], default='hardback', max_length=20, verbose_name='Cover Type'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.author', to_field='name', verbose_name='Author_Name'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='market.category', verbose_name='Category'),
        ),
    ]
